server:
  port: ${P2_NOTIF_PORT:8076}

spring:
  datasource:
    url: ${P2_NOTIF_DB_URL:jdbc:postgresql://localhost:5432/p2-db}
    username: ${P2_NOTIF_DB_USERNAME:postgres}
    password: ${P2_NOTIF_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html